version: "3.9"

services:
  server:
    build: /
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'qwerty'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=qwerty --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  my-db: